# Generated by Django 4.2.2 on 2023-06-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branch_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.IntegerField()),
                ('Institute', models.CharField(max_length=255)),
                ('Academic_Program_Name', models.CharField(max_length=255)),
                ('Quota', models.CharField(max_length=80)),
                ('Seat_Type', models.CharField(max_length=155)),
                ('Gender', models.CharField(max_length=155)),
                ('Opening_Rank', models.CharField(max_length=80)),
                ('Closing_Rank', models.CharField(max_length=80)),
                ('Year', models.CharField(max_length=155)),
                ('Round', models.IntegerField()),
            ],
        ),
    ]
