# Generated by Django 4.2.2 on 2023-06-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_branch_data_no_branch_data_sno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch_data',
            name='Sno',
        ),
        migrations.AlterField(
            model_name='branch_data',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
