# Generated by Django 4.2.2 on 2023-06-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_branch_data_sno_alter_branch_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_data',
            name='Gender',
            field=models.CharField(max_length=155, null=True),
        ),
    ]
